// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: seckill.proto
#ifndef GRPC_seckill_2eproto__INCLUDED
#define GRPC_seckill_2eproto__INCLUDED

#include "seckill.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace seckill {

class SeckillService final {
 public:
  static constexpr char const* service_full_name() {
    return "seckill.SeckillService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::seckill::SeckillResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::seckill::SeckillResponse>> Asyncseckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::seckill::SeckillResponse>>(AsyncseckillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::seckill::SeckillResponse>> PrepareAsyncseckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::seckill::SeckillResponse>>(PrepareAsyncseckillRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void seckill(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::seckill::SeckillResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void seckill(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::seckill::SeckillResponse>* AsyncseckillRaw(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::seckill::SeckillResponse>* PrepareAsyncseckillRaw(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::seckill::SeckillResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>> Asyncseckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>>(AsyncseckillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>> PrepareAsyncseckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>>(PrepareAsyncseckillRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, std::function<void(::grpc::Status)>) override;
      void seckill(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::seckill::SeckillResponse* response, std::function<void(::grpc::Status)>) override;
      void seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void seckill(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>* AsyncseckillRaw(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>* PrepareAsyncseckillRaw(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_seckill_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_seckill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_seckill() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_seckill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestseckill(::grpc::ServerContext* context, ::seckill::SeckillRequest* request, ::grpc::ServerAsyncResponseWriter< ::seckill::SeckillResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_seckill<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_seckill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_seckill() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::seckill::SeckillRequest, ::seckill::SeckillResponse>(
          [this](::grpc::ServerContext* context,
                 const ::seckill::SeckillRequest* request,
                 ::seckill::SeckillResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->seckill(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_seckill(
        ::grpc::experimental::MessageAllocator< ::seckill::SeckillRequest, ::seckill::SeckillResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::seckill::SeckillRequest, ::seckill::SeckillResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_seckill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_seckill<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_seckill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_seckill() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_seckill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_seckill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_seckill() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_seckill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestseckill(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_seckill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_seckill() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->seckill(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_seckill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void seckill(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_seckill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_seckill() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::seckill::SeckillRequest, ::seckill::SeckillResponse>(std::bind(&WithStreamedUnaryMethod_seckill<BaseClass>::Streamedseckill, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_seckill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedseckill(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::seckill::SeckillRequest,::seckill::SeckillResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_seckill<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_seckill<Service > StreamedService;
};

}  // namespace seckill


#endif  // GRPC_seckill_2eproto__INCLUDED
