// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: seckill.proto

#include "seckill.pb.h"
#include "seckill.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace seckill {

static const char* SeckillService_method_names[] = {
  "/seckill.SeckillService/seckill",
};

std::unique_ptr< SeckillService::Stub> SeckillService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SeckillService::Stub> stub(new SeckillService::Stub(channel));
  return stub;
}

SeckillService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_seckill_(SeckillService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SeckillService::Stub::seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::seckill::SeckillResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_seckill_, context, request, response);
}

void SeckillService::Stub::experimental_async::seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_seckill_, context, request, response, std::move(f));
}

void SeckillService::Stub::experimental_async::seckill(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::seckill::SeckillResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_seckill_, context, request, response, std::move(f));
}

void SeckillService::Stub::experimental_async::seckill(::grpc::ClientContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_seckill_, context, request, response, reactor);
}

void SeckillService::Stub::experimental_async::seckill(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::seckill::SeckillResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_seckill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>* SeckillService::Stub::AsyncseckillRaw(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::seckill::SeckillResponse>::Create(channel_.get(), cq, rpcmethod_seckill_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::seckill::SeckillResponse>* SeckillService::Stub::PrepareAsyncseckillRaw(::grpc::ClientContext* context, const ::seckill::SeckillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::seckill::SeckillResponse>::Create(channel_.get(), cq, rpcmethod_seckill_, context, request, false);
}

SeckillService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SeckillService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SeckillService::Service, ::seckill::SeckillRequest, ::seckill::SeckillResponse>(
          std::mem_fn(&SeckillService::Service::seckill), this)));
}

SeckillService::Service::~Service() {
}

::grpc::Status SeckillService::Service::seckill(::grpc::ServerContext* context, const ::seckill::SeckillRequest* request, ::seckill::SeckillResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace seckill

